### ISSUE TITLE
Multiple entities

### ISSUE THREAD

**Issue by DARKFiB3R** [edekeijzer/OctoPrint-PSUControl-HomeAssistant#10]
Is it possible to add multiple entities, so that I can also control my lighting separately?

Thanks.

**Comment by edekeijzer** [comment]
@DARKFiB3R as this is just an add-on for PSUControl, it is not possible (at least not for me) to create multiple power switches within OctoPrint. If toggling multiple entities at the same time would be helpful for you, a workaround could be to put them in a group, it would take me about 5 minutes to get that to work in this plug-in.

**Comment by ark-** [comment]
Group the lights, then call the `group.group_name` entity from this plugin

https://www.home-assistant.io/integrations/group

**Comment by edekeijzer** [comment]
> Group the lights in homeassistant (this is possible in the UI from the April update, see release notes here: https://www.home-assistant.io/blog/2022/04/06/release-20224/#now-available-in-the-ui-groups), then call the `group.group_name` entity from this plugin
> 
> https://www.home-assistant.io/integrations/group
> 

That would need a small modification to the code, since the endpoint is not _group/turn_on_ but _homeassistant/turn_on_. I'll probably be able to implement it this weekend.

**Comment by edekeijzer** [comment]
Just pushed the two lines of code to allow group entities and created a new release, but I think the preferred way to configure this within Home Assistant is to create a [switch group](https://www.home-assistant.io/integrations/group/#yaml-configuration).
