### ISSUE TITLE
How connect PSU Control to my Plug connected on home assistant

### ISSUE THREAD

**Issue by BeppeTemp** [edekeijzer/OctoPrint-PSUControl-HomeAssistant#13]
Hi, I don't understand how the plugin should work, currently I have PSU Control and PSU Controll Home assistant installed on my Octoprint, the printer is connected to a properly configured xiaomi smart plug with home assistant, I don't understand how I should now tell a PSU Controll to turn off the plug when printing is finished.

**Comment by edekeijzer** [comment]
Configure the [Power Off Options](https://github.com/kantlivelong/OctoPrint-PSUControl/wiki/Settings#power-off-options) in the main PSUControl plugin. The HomeAssistant part is just an add-on that allows PSUControl to switch an HA entity on and off instead of Raspberry Pi GPIO pins.
