### ISSUE TITLE
Plugin not enabling

### ISSUE THREAD

**Issue by jamesdangercarpenter** [edekeijzer/OctoPrint-PSUControl-HomeAssistant#7]
Hi, love the idea but unfortunately when I enable the plugin it doesn't appear under PSU control or plugins, so I can't configure or use it.

Any ideas?

**Comment by edekeijzer** [comment]
- Did you restart after installing?
- Are you running Octoprint on Python 3?
- Were you able to install from the menu or did you copy the link to the plugin installer?
- If you are running on Python 3, what do the logs say?

**Comment by jamesdangercarpenter** [comment]
You know what, I totally assumed I was running it on python3, but I'm actually on python2.... Thanks for the idiot check <3
